### ISSUE TITLE
BrokenPipeError when using pipe with head

### ISSUE THREAD

**Issue by bitcanon** [bitcanon/macloot#1]
When running the command:
`macloot -s cisco | head`

Exception is throws:
```
Traceback (most recent call last):
  File "/home/mikael/.local/bin/macloot", line 8, in <module>
    sys.exit(main())
  File "/home/mikael/.local/lib/python3.9/site-packages/macloot.py", line 352, in main
    process_mac_addresses(mac_list=macs, args=args)
  File "/home/mikael/.local/lib/python3.9/site-packages/macloot.py", line 260, in process_mac_addresses
    print(output)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by bitcanon** [comment]
This issue is resolved since rebuilding the CSV database connector.

**Comment by bitcanon** [comment]
Issue remains.
